# Generated by Django 4.2.7 on 2025-08-12 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('event_type', models.CharField(choices=[('login_success', '로그인 성공'), ('login_failed', '로그인 실패'), ('logout', '로그아웃'), ('password_change', '비밀번호 변경'), ('permission_denied', '권한 거부'), ('suspicious_activity', '의심스러운 활동'), ('sql_injection_attempt', 'SQL Injection 시도'), ('xss_attempt', 'XSS 시도'), ('csrf_failure', 'CSRF 실패')], max_length=50, verbose_name='이벤트 유형')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('path', models.CharField(max_length=255, verbose_name='요청 경로')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP 메서드')),
                ('details', models.JSONField(default=dict, verbose_name='상세 정보')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '보안 로그',
                'verbose_name_plural': '보안 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='core_securi_event_t_61f4f6_idx'), models.Index(fields=['user', '-created_at'], name='core_securi_user_id_7fd1c6_idx'), models.Index(fields=['ip_address', '-created_at'], name='core_securi_ip_addr_929326_idx')],
            },
        ),
    ]
