# Generated by Django 5.2.4 on 2025-08-02 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='정책 제목')),
                ('description', models.TextField(verbose_name='정책 설명')),
                ('rebate_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='기본 리베이트율 (%)')),
                ('reception_type', models.CharField(choices=[('general', '일반'), ('link', '링크'), ('registration', '등록'), ('egg', '에그')], max_length=20, verbose_name='접수 방식')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML 내용')),
                ('is_shared', models.BooleanField(default=False, verbose_name='공유 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='등록 업체')),
            ],
            options={
                'verbose_name': '정책',
                'verbose_name_plural': '정책',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_rebate_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='커스텀 리베이트율 (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='배정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='배정 업체')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy', verbose_name='정책')),
            ],
            options={
                'verbose_name': '정책 배정',
                'verbose_name_plural': '정책 배정',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_rebate_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='공유 리베이트율 (%)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='공유 요청일시')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('source_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to='policies.policy', verbose_name='원본 정책')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='대상 업체')),
            ],
            options={
                'verbose_name': '정책 공유',
                'verbose_name_plural': '정책 공유',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company'], name='policies_po_company_d3469b_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['reception_type'], name='policies_po_recepti_89eb28_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['is_shared'], name='policies_po_is_shar_6e1128_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['is_active'], name='policies_po_is_acti_d21de8_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['created_at'], name='policies_po_created_23231a_idx'),
        ),
        migrations.AddIndex(
            model_name='policyassignment',
            index=models.Index(fields=['policy'], name='policies_po_policy__139a16_idx'),
        ),
        migrations.AddIndex(
            model_name='policyassignment',
            index=models.Index(fields=['company'], name='policies_po_company_5ef4de_idx'),
        ),
        migrations.AddIndex(
            model_name='policyassignment',
            index=models.Index(fields=['is_active'], name='policies_po_is_acti_c7c463_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyassignment',
            unique_together={('policy', 'company')},
        ),
        migrations.AddIndex(
            model_name='policyshare',
            index=models.Index(fields=['source_policy'], name='policies_po_source__8fedde_idx'),
        ),
        migrations.AddIndex(
            model_name='policyshare',
            index=models.Index(fields=['target_company'], name='policies_po_target__68b9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='policyshare',
            index=models.Index(fields=['is_approved'], name='policies_po_is_appr_82b435_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyshare',
            unique_together={('source_policy', 'target_company')},
        ),
    ]
