# Generated by Django 4.2.7 on 2025-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyassignment',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='정책이 할당된 회사의 이름', max_length=200, null=True, verbose_name='할당된 회사 이름'),
        ),
    ]
