# Generated by Django 4.2.7 on 2025-08-12 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('policies', '0002_policyassignment_assigned_to_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyExposure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('exposed_at', models.DateTimeField(auto_now_add=True, verbose_name='노출 시작일')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposed_policies', to='companies.company', verbose_name='협력사')),
                ('exposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='노출 설정자')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='policies.policy', verbose_name='정책')),
            ],
            options={
                'verbose_name': '정책 노출',
                'verbose_name_plural': '정책 노출 관리',
                'ordering': ['-exposed_at'],
                'unique_together': {('policy', 'agency')},
            },
        ),
        migrations.CreateModel(
            name='OrderFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='양식 제목')),
                ('description', models.TextField(blank=True, verbose_name='양식 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_form', to='policies.policy', verbose_name='정책')),
            ],
            options={
                'verbose_name': '주문서 양식',
                'verbose_name_plural': '주문서 양식 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, verbose_name='필드 이름')),
                ('field_label', models.CharField(max_length=200, verbose_name='필드 라벨')),
                ('field_type', models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('select', '선택'), ('radio', '라디오'), ('checkbox', '체크박스'), ('textarea', '텍스트 영역'), ('date', '날짜'), ('rebate_table', '리베이트 테이블')], max_length=20, verbose_name='필드 타입')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수 여부')),
                ('field_options', models.JSONField(blank=True, null=True, verbose_name='필드 옵션')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='플레이스홀더')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='도움말')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='policies.orderformtemplate', verbose_name='양식 템플릿')),
            ],
            options={
                'verbose_name': '주문서 필드',
                'verbose_name_plural': '주문서 필드 관리',
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyRebate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rebate_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='리베이트 금액')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('policy_exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebates', to='policies.policyexposure', verbose_name='노출된 정책')),
                ('retail_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_rebates', to='companies.company', verbose_name='판매점')),
            ],
            options={
                'verbose_name': '협력사 리베이트',
                'verbose_name_plural': '협력사 리베이트 설정',
                'ordering': ['-created_at'],
                'unique_together': {('policy_exposure', 'retail_company')},
            },
        ),
    ]
