# Generated by Django 4.2.7 on 2025-08-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_rebatematrix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rebatematrix',
            new_name='policies_re_policy__fc64c0_idx',
            old_name='policies_re_policy__b7c4f6_idx',
        ),
        migrations.RenameIndex(
            model_name='rebatematrix',
            new_name='policies_re_plan_ra_7b22f5_idx',
            old_name='policies_re_plan_ra_d6e3f8_idx',
        ),
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('draft', '초안'), ('active', '활성'), ('inactive', '비활성'), ('expired', '만료')], default='draft', help_text='정책의 상태를 선택하세요', max_length=20, verbose_name='정책 상태'),
        ),
        migrations.AddField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('normal', '일반'), ('special', '특별'), ('event', '이벤트')], default='normal', help_text='정책의 타입을 선택하세요', max_length=20, verbose_name='정책 타입'),
        ),
    ]
