# Generated by Django 4.2.7 on 2025-08-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('policies', '0005_rename_policies_re_policy__b7c4f6_idx_policies_re_policy__fc64c0_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rebatematrix',
            options={'ordering': ['policy', 'plan_range', 'contract_period'], 'verbose_name': '리베이트 매트릭스', 'verbose_name_plural': '리베이트 매트릭스'},
        ),
        migrations.RemoveIndex(
            model_name='rebatematrix',
            name='policies_re_policy__fc64c0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rebatematrix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='policy',
            name='join_type',
            field=models.CharField(choices=[('number_transfer', '번호이동'), ('device_change', '기기변경'), ('new_subscription', '신규가입'), ('all', '전체')], default='all', help_text='적용할 가입유형을 선택하세요', max_length=20, verbose_name='가입유형'),
        ),
        migrations.AlterField(
            model_name='policyexposure',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposed_policies', to='companies.company', verbose_name='노출 업체'),
        ),
        migrations.AlterField(
            model_name='rebatematrix',
            name='contract_period',
            field=models.IntegerField(choices=[(12, '12개월'), (24, '24개월')], help_text='리베이트가 적용될 계약기간 (개월)', verbose_name='계약기간'),
        ),
        migrations.AlterField(
            model_name='rebatematrix',
            name='plan_range',
            field=models.IntegerField(choices=[(11000, '11K'), (15000, '15K'), (20000, '20K'), (25000, '25K'), (30000, '30K'), (35000, '35K'), (40000, '40K'), (45000, '45K'), (50000, '50K'), (55000, '55K'), (60000, '60K'), (65000, '65K'), (70000, '70K'), (75000, '75K'), (80000, '80K'), (85000, '85K'), (90000, '90K'), (95000, '95K'), (99000, '99K')], help_text='리베이트가 적용될 요금제 금액 (K 단위)', verbose_name='요금제 금액'),
        ),
        migrations.AlterUniqueTogether(
            name='rebatematrix',
            unique_together={('policy', 'plan_range', 'contract_period')},
        ),
        migrations.AddIndex(
            model_name='rebatematrix',
            index=models.Index(fields=['policy'], name='policies_re_policy__0386a8_idx'),
        ),
        migrations.RemoveField(
            model_name='rebatematrix',
            name='carrier',
        ),
    ]
