# Generated by Django 4.2.7 on 2025-08-17 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0006_add_join_type_and_update_rebate_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='요금제의 고유 식별자', primary_key=True, serialize=False)),
                ('carrier', models.CharField(choices=[('skt', 'SKT'), ('kt', 'KT'), ('lg', 'LG U+')], help_text='요금제를 제공하는 통신사', max_length=10, verbose_name='통신사')),
                ('plan_name', models.CharField(help_text='요금제의 이름', max_length=200, verbose_name='요금제명')),
                ('plan_price', models.IntegerField(help_text='월 요금제 금액 (원)', verbose_name='요금제 금액')),
                ('description', models.TextField(blank=True, help_text='요금제에 대한 상세 설명', verbose_name='요금제 설명')),
                ('is_active', models.BooleanField(default=True, help_text='요금제 사용 가능 여부', verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '통신사 요금제',
                'verbose_name_plural': '통신사 요금제 관리',
                'ordering': ['carrier', 'plan_price', 'plan_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='기기 색상의 고유 식별자', primary_key=True, serialize=False)),
                ('color_name', models.CharField(help_text='색상의 이름', max_length=100, verbose_name='색상명')),
                ('color_code', models.CharField(blank=True, help_text='색상의 HEX 코드 (예: #FF0000)', max_length=7, verbose_name='색상 코드')),
                ('is_active', models.BooleanField(default=True, help_text='색상 선택 가능 여부', verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '기기 색상',
                'verbose_name_plural': '기기 색상 관리',
                'ordering': ['device_model', 'color_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='기기 모델의 고유 식별자', primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='기기의 모델명', max_length=200, verbose_name='모델명')),
                ('manufacturer', models.CharField(help_text='기기 제조사', max_length=100, verbose_name='제조사')),
                ('description', models.TextField(blank=True, help_text='기기 모델에 대한 상세 설명', verbose_name='모델 설명')),
                ('is_active', models.BooleanField(default=True, help_text='모델 판매 가능 여부', verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '기기 모델',
                'verbose_name_plural': '기기 모델 관리',
                'ordering': ['manufacturer', 'model_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rebatematrix',
            options={'ordering': ['policy', 'carrier', 'plan_range', 'contract_period'], 'verbose_name': '리베이트 매트릭스', 'verbose_name_plural': '리베이트 매트릭스'},
        ),
        migrations.RemoveIndex(
            model_name='rebatematrix',
            name='policies_re_plan_ra_7b22f5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rebatematrix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rebatematrix',
            name='carrier',
            field=models.CharField(choices=[('skt', 'SKT'), ('kt', 'KT'), ('lg', 'LG U+'), ('all', '전체')], default='all', help_text='리베이트가 적용될 통신사', max_length=10, verbose_name='통신사'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='field_type',
            field=models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('select', '선택'), ('radio', '라디오'), ('checkbox', '체크박스'), ('textarea', '텍스트 영역'), ('date', '날짜'), ('phone', '전화번호'), ('email', '이메일'), ('carrier_plan', '통신사 요금제'), ('device_model', '기기 모델'), ('device_color', '기기 색상'), ('sim_type', '유심 타입'), ('contract_period', '계약 기간'), ('payment_method', '결제 방법'), ('rebate_table', '리베이트 테이블')], max_length=20, verbose_name='필드 타입'),
        ),
        migrations.AlterUniqueTogether(
            name='rebatematrix',
            unique_together={('policy', 'carrier', 'plan_range', 'contract_period')},
        ),
        migrations.AddIndex(
            model_name='rebatematrix',
            index=models.Index(fields=['carrier', 'plan_range', 'contract_period'], name='policies_re_carrier_134dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='rebatematrix',
            index=models.Index(fields=['policy', 'carrier'], name='policies_re_policy__fc64c0_idx'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='모델을 생성한 관리자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='devicecolor',
            name='device_model',
            field=models.ForeignKey(help_text='색상이 적용될 기기 모델', on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='policies.devicemodel', verbose_name='기기 모델'),
        ),
        migrations.AddField(
            model_name='carrierplan',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='요금제를 생성한 관리자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['manufacturer', 'is_active'], name='policies_de_manufac_5bcc28_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['model_name'], name='policies_de_model_n_087d92_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['created_at'], name='policies_de_created_d0f1af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemodel',
            unique_together={('manufacturer', 'model_name')},
        ),
        migrations.AddIndex(
            model_name='devicecolor',
            index=models.Index(fields=['device_model', 'is_active'], name='policies_de_device__6f77b2_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecolor',
            index=models.Index(fields=['color_name'], name='policies_de_color_n_e8f4a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecolor',
            unique_together={('device_model', 'color_name')},
        ),
        migrations.AddIndex(
            model_name='carrierplan',
            index=models.Index(fields=['carrier', 'is_active'], name='policies_ca_carrier_09afb1_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierplan',
            index=models.Index(fields=['plan_price'], name='policies_ca_plan_pr_a84254_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierplan',
            index=models.Index(fields=['created_at'], name='policies_ca_created_1d3df2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carrierplan',
            unique_together={('carrier', 'plan_name')},
        ),
    ]
