# Generated by Django 4.2.7 on 2025-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_carrierplan_devicecolor_devicemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderformfield',
            name='field_type',
            field=models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('select', '선택'), ('radio', '라디오'), ('checkbox', '체크박스'), ('textarea', '텍스트 영역'), ('date', '날짜'), ('phone', '전화번호'), ('email', '이메일'), ('carrier_plan', '통신사 요금제'), ('device_model', '기기 모델'), ('device_color', '기기 색상'), ('sim_type', '유심 타입'), ('contract_period', '계약 기간'), ('payment_method', '결제 방법'), ('rebate_table', '리베이트 테이블'), ('course', '코스'), ('common_support', '공통지원금'), ('additional_support', '추가지원금'), ('free_amount', '프리금액'), ('installment_principal', '할부원금'), ('additional_fee', '부가'), ('insurance', '보험'), ('welfare', '복지'), ('legal_info', '법대정보'), ('foreigner_info', '외국인정보'), ('installment_months', '할부개월수'), ('join_type', '가입유형')], max_length=30, verbose_name='필드 타입'),
        ),
    ]
