# Generated by Django 4.2.7 on 2025-08-17 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('policies', '0008_alter_orderformfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebatematrix',
            name='contract_period',
            field=models.IntegerField(choices=[(12, '12개월'), (24, '24개월'), (36, '36개월'), (48, '48개월')], help_text='리베이트가 적용될 계약기간 (개월)', verbose_name='계약기간'),
        ),
        migrations.AlterField(
            model_name='rebatematrix',
            name='plan_range',
            field=models.IntegerField(choices=[(11000, '11K'), (22000, '22K'), (33000, '33K'), (44000, '44K'), (55000, '55K'), (66000, '66K'), (77000, '77K'), (88000, '88K'), (99000, '99K'), (110000, '110K'), (121000, '121K'), (132000, '132K'), (143000, '143K'), (154000, '154K'), (165000, '165K')], help_text='리베이트가 적용될 요금제 금액 (K 단위)', verbose_name='요금제 금액'),
        ),
        migrations.CreateModel(
            name='AgencyRebateMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='협력사 리베이트 매트릭스의 고유 식별자', primary_key=True, serialize=False)),
                ('carrier', models.CharField(choices=[('skt', 'SKT'), ('kt', 'KT'), ('lg', 'LG U+'), ('all', '전체')], default='all', help_text='리베이트가 적용될 통신사', max_length=10, verbose_name='통신사')),
                ('plan_range', models.IntegerField(choices=[(11000, '11K'), (22000, '22K'), (33000, '33K'), (44000, '44K'), (55000, '55K'), (66000, '66K'), (77000, '77K'), (88000, '88K'), (99000, '99K'), (110000, '110K'), (121000, '121K'), (132000, '132K'), (143000, '143K'), (154000, '154K'), (165000, '165K')], help_text='리베이트가 적용될 요금제 금액 (K 단위)', verbose_name='요금제 금액')),
                ('contract_period', models.IntegerField(choices=[(12, '12개월'), (24, '24개월'), (36, '36개월'), (48, '48개월')], help_text='리베이트가 적용될 계약기간 (개월)', verbose_name='계약기간')),
                ('rebate_amount', models.DecimalField(decimal_places=2, help_text='해당 조건의 리베이트 금액', max_digits=10, verbose_name='리베이트 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('agency', models.ForeignKey(help_text='리베이트를 설정하는 협력사', on_delete=django.db.models.deletion.CASCADE, related_name='rebate_matrices', to='companies.company', verbose_name='협력사')),
                ('policy', models.ForeignKey(help_text='리베이트 매트릭스가 속한 정책', on_delete=django.db.models.deletion.CASCADE, related_name='agency_rebate_matrix', to='policies.policy', verbose_name='정책')),
            ],
            options={
                'verbose_name': '협력사 리베이트 매트릭스',
                'verbose_name_plural': '협력사 리베이트 매트릭스',
                'ordering': ['policy', 'agency', 'plan_range', 'contract_period'],
                'indexes': [models.Index(fields=['policy'], name='policies_ag_policy__4add9a_idx'), models.Index(fields=['agency'], name='policies_ag_agency__a9e978_idx'), models.Index(fields=['policy', 'agency'], name='policies_ag_policy__6c3810_idx')],
                'unique_together': {('policy', 'agency', 'carrier', 'plan_range', 'contract_period')},
            },
        ),
    ]
