# Generated by Django 4.2.7 on 2025-08-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_alter_rebatematrix_contract_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='정책의 활성화 여부', verbose_name='활성화 여부'),
        ),
    ]
