# Generated by Django 4.2.7 on 2025-08-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_policy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderformfield',
            name='accept',
            field=models.CharField(blank=True, default='image/*,.pdf,.doc,.docx', max_length=200, verbose_name='허용 파일 타입'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='allow_manual',
            field=models.BooleanField(default=True, verbose_name='수기 입력 허용'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='auto_fill',
            field=models.CharField(blank=True, max_length=50, verbose_name='자동 채우기 타입'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='auto_generate',
            field=models.BooleanField(default=False, verbose_name='자동 생성'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='data_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='데이터 소스'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='is_masked',
            field=models.BooleanField(default=False, verbose_name='마스킹 여부'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='is_readonly',
            field=models.BooleanField(default=False, verbose_name='읽기 전용'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='max_files',
            field=models.IntegerField(default=4, verbose_name='최대 파일 수'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='multiple',
            field=models.BooleanField(default=False, verbose_name='다중 선택'),
        ),
        migrations.AddField(
            model_name='orderformfield',
            name='rows',
            field=models.IntegerField(default=3, verbose_name='textarea 행 수'),
        ),
        migrations.AlterField(
            model_name='orderformfield',
            name='field_type',
            field=models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('select', '선택'), ('radio', '라디오'), ('checkbox', '체크박스'), ('textarea', '텍스트 영역'), ('date', '날짜'), ('datetime', '날짜/시간'), ('phone', '전화번호'), ('email', '이메일'), ('url', 'URL'), ('barcode_scan', '바코드 스캔'), ('large_textarea', '대형 텍스트 영역'), ('dropdown_from_policy', '정책 드롭다운'), ('file_upload', '파일 업로드'), ('customer_type', '고객유형'), ('carrier_plan', '통신사 요금제'), ('device_model', '기기 모델'), ('device_color', '기기 색상'), ('sim_type', '유심 타입'), ('contract_period', '계약 기간'), ('payment_method', '결제 방법'), ('rebate_table', '리베이트 테이블'), ('course', '코스'), ('common_support', '공통지원금'), ('additional_support', '추가지원금'), ('free_amount', '프리금액'), ('installment_principal', '할부원금'), ('additional_fee', '부가'), ('insurance', '보험'), ('welfare', '복지'), ('legal_info', '법대정보'), ('foreigner_info', '외국인정보'), ('installment_months', '할부개월수'), ('join_type', '가입유형')], max_length=30, verbose_name='필드 타입'),
        ),
    ]
