# Generated by Django 4.2.7 on 2025-08-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_orderformfield_accept_orderformfield_allow_manual_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RebateMatrix',
            new_name='CommissionMatrix',
        ),
        migrations.RenameIndex(
            model_name='commissionmatrix',
            new_name='policies_co_policy__711022_idx',
            old_name='policies_re_policy__0386a8_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionmatrix',
            new_name='policies_co_carrier_9a0ed5_idx',
            old_name='policies_re_carrier_134dc1_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionmatrix',
            new_name='policies_co_policy__7ae51f_idx',
            old_name='policies_re_policy__fc64c0_idx',
        ),
    ]
