# Generated by Django 4.2.7 on 2025-08-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_rename_rebatematrix_commissionmatrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='external_url',
            field=models.URLField(blank=True, help_text='정책 상세 안내 또는 외부 라우팅 URL (선택)', max_length=500, null=True, verbose_name='정책 URL'),
        ),
    ]
