# Generated by Django 4.2.7 on 2025-08-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0006_commission_fact_table'),
        ('settlements', '0006_commission_grade_system'),
    ]

    operations = [
    ]
