# Generated by Django 4.2.7 on 2025-08-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0007_merge_20250824_1413'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='settlement',
            name='settlements_expected_payment_idx',
        ),
        migrations.RemoveIndex(
            model_name='settlement',
            name='settlements_payment_method_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionfact',
            new_name='settlements_date_ke_637f58_idx',
            old_name='settlements_commissionfact_date_company_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionfact',
            new_name='settlements_date_ke_ba08ad_idx',
            old_name='settlements_commissionfact_date_policy_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionfact',
            new_name='settlements_company_ff0d95_idx',
            old_name='settlements_commissionfact_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionfact',
            new_name='settlements_policy__fdd463_idx',
            old_name='settlements_commissionfact_policy_date_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionfact',
            new_name='settlements_carrier_3bb2b9_idx',
            old_name='settlements_commissionfact_carrier_plan_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionfact',
            new_name='settlements_achieve_c7fec2_idx',
            old_name='settlements_commissionfact_grade_level_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionfact',
            new_name='settlements_batch_i_9b3163_idx',
            old_name='settlements_commissionfact_batch_id_idx',
        ),
        migrations.RenameIndex(
            model_name='commissiongradetracking',
            new_name='settlements_company_75be3a_idx',
            old_name='settlements_commissiongradetracking_company_period_idx',
        ),
        migrations.RenameIndex(
            model_name='commissiongradetracking',
            new_name='settlements_policy__97e460_idx',
            old_name='settlements_commissiongradetracking_policy_period_idx',
        ),
        migrations.RenameIndex(
            model_name='commissiongradetracking',
            new_name='settlements_achieve_6ac4de_idx',
            old_name='settlements_commissiongradetracking_grade_level_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeachievementhistory',
            new_name='settlements_grade_t_034c1f_idx',
            old_name='settlements_gradeachievementhistory_tracking_achieved_idx',
        ),
        migrations.RenameIndex(
            model_name='gradeachievementhistory',
            new_name='settlements_to_leve_bc0c05_idx',
            old_name='settlements_gradeachievementhistory_to_level_idx',
        ),
        migrations.RenameIndex(
            model_name='gradebonussettlement',
            new_name='settlements_grade_t_a84cb5_idx',
            old_name='settlements_gradebonussettlement_tracking_status_idx',
        ),
        migrations.RenameIndex(
            model_name='gradebonussettlement',
            new_name='settlements_status_e69b3b_idx',
            old_name='settlements_gradebonussettlement_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementstatushistory',
            new_name='settlements_settlem_702bc9_idx',
            old_name='settlements_settlement_history_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementstatushistory',
            new_name='settlements_to_stat_bd2c55_idx',
            old_name='settlements_settlement_status_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementstatushistory',
            new_name='settlements_changed_0471a0_idx',
            old_name='settlements_settlement_user_idx',
        ),
    ]
