# Generated by Django 5.2.4 on 2025-08-02 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('phone', '휴대폰'), ('tablet', '태블릿'), ('laptop', '노트북'), ('desktop', '데스크톱'), ('accessory', '액세서리'), ('other', '기타')], max_length=20, verbose_name='기기 유형')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델명')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='시리얼번호')),
                ('status', models.CharField(choices=[('available', '사용가능'), ('in_use', '사용중'), ('maintenance', '정비중'), ('retired', '폐기')], default='available', max_length=20, verbose_name='상태')),
                ('purchase_date', models.DateField(verbose_name='구매일')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='보증만료일')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='소유 업체')),
            ],
            options={
                'verbose_name': '기기',
                'verbose_name_plural': '기기',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('checkout', '대여'), ('checkin', '반납'), ('maintenance', '정비'), ('repair', '수리'), ('retire', '폐기')], max_length=20, verbose_name='로그 유형')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='처리일시')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', verbose_name='기기')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser', verbose_name='처리자')),
            ],
            options={
                'verbose_name': '기기 로그',
                'verbose_name_plural': '기기 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('product_code', models.CharField(max_length=100, verbose_name='상품코드')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('min_stock', models.IntegerField(default=0, verbose_name='최소재고')),
                ('max_stock', models.IntegerField(default=1000, verbose_name='최대재고')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='보관위치')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='소유 업체')),
            ],
            options={
                'verbose_name': '재고',
                'verbose_name_plural': '재고',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('in', '입고'), ('out', '출고'), ('adjustment', '조정'), ('return', '반품')], max_length=20, verbose_name='거래 유형')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='참조번호')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='거래일시')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='재고')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser', verbose_name='처리자')),
            ],
            options={
                'verbose_name': '재고 거래',
                'verbose_name_plural': '재고 거래',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company'], name='inventory_d_company_1673ed_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='inventory_d_device__82f1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='inventory_d_status_458222_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='inventory_d_serial__ed8962_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['device'], name='inventory_d_device__aef2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['log_type'], name='inventory_d_log_typ_d95e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['user'], name='inventory_d_user_id_297999_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['created_at'], name='inventory_d_created_472c47_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['company'], name='inventory_i_company_331b33_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_code'], name='inventory_i_product_7341f8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity'], name='inventory_i_quantit_ef61d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('company', 'product_code')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['inventory'], name='inventory_i_invento_b5a407_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_i_transac_2eccee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['user'], name='inventory_i_user_id_952fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='inventory_i_created_670884_idx'),
        ),
    ]
