# Generated by Django 4.2.7 on 2025-08-06 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('lms', 'LMS'), ('mms', 'MMS')], max_length=10, verbose_name='메시지 유형')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='수신번호')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('status', models.CharField(choices=[('pending', '발송대기'), ('sending', '발송중'), ('sent', '발송완료'), ('failed', '발송실패'), ('cancelled', '발송취소')], default='pending', max_length=20, verbose_name='발송 상태')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='외부 시스템 ID')),
                ('error_message', models.TextField(blank=True, verbose_name='에러 메시지')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='발송 업체')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser', verbose_name='발송자')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('template_type', models.CharField(choices=[('order_status', '주문상태'), ('approval', '승인'), ('notification', '알림'), ('marketing', '마케팅'), ('custom', '커스텀')], max_length=20, verbose_name='템플릿 유형')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('variables', models.JSONField(default=dict, verbose_name='변수 목록')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser', verbose_name='생성자')),
            ],
            options={
                'verbose_name': '메시지 템플릿',
                'verbose_name_plural': '메시지 템플릿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, verbose_name='액션')),
                ('status', models.CharField(max_length=20, verbose_name='상태')),
                ('details', models.JSONField(default=dict, verbose_name='상세 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='로그일시')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.message', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '메시지 로그',
                'verbose_name_plural': '메시지 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.messagetemplate', verbose_name='템플릿'),
        ),
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('lms', 'LMS'), ('mms', 'MMS')], max_length=10, verbose_name='메시지 유형')),
                ('recipients', models.JSONField(verbose_name='수신자 목록')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('total_count', models.IntegerField(default=0, verbose_name='총 발송 수')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 수')),
                ('failed_count', models.IntegerField(default=0, verbose_name='실패 수')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='발송 업체')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser', verbose_name='발송자')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.messagetemplate', verbose_name='템플릿')),
            ],
            options={
                'verbose_name': '일괄 메시지',
                'verbose_name_plural': '일괄 메시지',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(verbose_name='예약 발송일시')),
                ('is_sent', models.BooleanField(default=False, verbose_name='발송 여부')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='실제 발송일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='예약일시')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messaging.message', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '예약 메시지',
                'verbose_name_plural': '예약 메시지',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['scheduled_at'], name='messaging_s_schedul_cb9ffb_idx'), models.Index(fields=['is_sent'], name='messaging_s_is_sent_3fbcfe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['template_type'], name='messaging_m_templat_fb237f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['is_active'], name='messaging_m_is_acti_443b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['created_by'], name='messaging_m_created_5667db_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['message'], name='messaging_m_message_683045_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['action'], name='messaging_m_action_49bac1_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['status'], name='messaging_m_status_cdf57d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['created_at'], name='messaging_m_created_ce7090_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='messaging_m_message_9677d2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='messaging_m_status_7d189b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient_phone'], name='messaging_m_recipie_2210a8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_by'], name='messaging_m_sent_by_b4f606_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['company'], name='messaging_m_company_183f85_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='messaging_m_created_d51bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkmessage',
            index=models.Index(fields=['message_type'], name='messaging_b_message_69a419_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkmessage',
            index=models.Index(fields=['sent_by'], name='messaging_b_sent_by_4d5cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkmessage',
            index=models.Index(fields=['company'], name='messaging_b_company_64f9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkmessage',
            index=models.Index(fields=['is_completed'], name='messaging_b_is_comp_e0bdf0_idx'),
        ),
    ]
