# Generated by Django 4.2.7 on 2025-08-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='업체 코드')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('type', models.CharField(choices=[('headquarters', '본사'), ('agency', '협력사'), ('dealer', '대리점'), ('retail', '판매점')], max_length=20, verbose_name='업체 유형')),
                ('status', models.BooleanField(default=True, verbose_name='운영 상태')),
                ('visible', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('default_courier', models.CharField(blank=True, max_length=50, verbose_name='기본 택배사')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='상위 업체')),
            ],
            options={
                'verbose_name': '업체',
                'verbose_name_plural': '업체',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자명')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('staff', '직원')], max_length=10, verbose_name='역할')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거절됨')], default='pending', max_length=20, verbose_name='승인 상태')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='소속 업체')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django 사용자')),
            ],
            options={
                'verbose_name': '업체 사용자',
                'verbose_name_plural': '업체 사용자',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='companies_c_usernam_cb50b3_idx'), models.Index(fields=['company'], name='companies_c_company_b6de3c_idx'), models.Index(fields=['role'], name='companies_c_role_7825c9_idx'), models.Index(fields=['status'], name='companies_c_status_e9c83d_idx'), models.Index(fields=['is_approved'], name='companies_c_is_appr_710c02_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('message_type', models.CharField(choices=[('notice', '공지사항'), ('policy', '정책안내'), ('alert', '알림')], max_length=20, verbose_name='메시지 유형')),
                ('is_bulk', models.BooleanField(default=False, verbose_name='일괄 발송 여부')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='수신 업체')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='발송자')),
            ],
            options={
                'verbose_name': '업체 메시지',
                'verbose_name_plural': '업체 메시지',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['message_type'], name='companies_c_message_8b0c92_idx'), models.Index(fields=['is_bulk'], name='companies_c_is_bulk_4f8ff4_idx'), models.Index(fields=['company'], name='companies_c_company_c8c730_idx'), models.Index(fields=['sent_at'], name='companies_c_sent_at_b4dc7f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='companies_c_code_871b04_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['type'], name='companies_c_type_93849c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['parent_company'], name='companies_c_parent__04bbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='companies_c_status_2407e4_idx'),
        ),
    ]
