# Generated by Django 4.2.7 on 2025-07-22 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='업체의 고유 식별자', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='업체의 정식 명칭', max_length=200, verbose_name='업체명')),
                ('type', models.CharField(choices=[('agency', '대리점'), ('retail', '판매점')], help_text='대리점 또는 판매점 구분', max_length=10, verbose_name='업체 타입')),
                ('status', models.BooleanField(default=True, help_text='업체 운영 여부 (True: 운영중, False: 중단)', verbose_name='운영 상태')),
                ('visible', models.BooleanField(default=True, help_text='하부 업체에 노출할지 여부', verbose_name='노출 여부')),
                ('default_courier', models.CharField(blank=True, help_text='주문 처리 시 기본으로 사용할 택배사', max_length=100, null=True, verbose_name='기본 택배사')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '업체',
                'verbose_name_plural': '업체 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='로그인에 사용할 사용자명', max_length=150, unique=True, verbose_name='사용자명')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('staff', '직원')], default='staff', help_text='사용자의 권한 레벨', max_length=10, verbose_name='역할')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('company', models.ForeignKey(help_text='사용자가 소속된 업체', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company', verbose_name='소속 업체')),
            ],
            options={
                'verbose_name': '업체 사용자',
                'verbose_name_plural': '업체 사용자 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='업체에 전송할 메시지 내용', verbose_name='메시지 내용')),
                ('is_bulk', models.BooleanField(default=False, help_text='모든 업체에 일괄 발송인지 개별 발송인지 구분', verbose_name='일괄 발송 여부')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('company', models.ForeignKey(blank=True, help_text='메시지를 받을 업체 (일괄 발송 시에는 null)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='companies.company', verbose_name='수신 업체')),
                ('sent_by', models.ForeignKey(blank=True, help_text='메시지를 발송한 관리자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='발송자')),
            ],
            options={
                'verbose_name': '업체 메시지',
                'verbose_name_plural': '업체 메시지 목록',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['type', 'status'], name='companies_c_type_64d26f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_c_name_2d8260_idx'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['username'], name='companies_c_usernam_cb50b3_idx'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['company', 'role'], name='companies_c_company_761903_idx'),
        ),
        migrations.AddIndex(
            model_name='companymessage',
            index=models.Index(fields=['company', 'sent_at'], name='companies_c_company_a4585c_idx'),
        ),
        migrations.AddIndex(
            model_name='companymessage',
            index=models.Index(fields=['is_bulk', 'sent_at'], name='companies_c_is_bulk_05167f_idx'),
        ),
    ]
