# Generated by Django 4.2.7 on 2025-07-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='본사, 납품업체, 협력사 중 상위 업체', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_companies', to='companies.company', verbose_name='상위 업체'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('headquarters', '본사'), ('agency', '협력사'), ('retail', '판매점')], help_text='본사, 납품업체, 협력사 또는 판매점 구분', max_length=20, verbose_name='업체 유형'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['parent_company'], name='companies_c_parent__04bbdb_idx'),
        ),
    ]
