# Generated by Django 5.2.4 on 2025-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='업체 코드'),
        ),
    ]
