# Generated by Django 4.2.7 on 2025-08-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='settlement',
            new_name='settlements_order_i_a9932d_idx',
            old_name='settlements_order_i_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='settlements_company_dc0da0_idx',
            old_name='settlements_company_def456_idx',
        ),
        migrations.RenameIndex(
            model_name='settlement',
            new_name='settlements_status_8c7d7a_idx',
            old_name='settlements_status_ghi789_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementbatch',
            new_name='settlements_start_d_b5f379_idx',
            old_name='settlements_batch_jkl012_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementbatch',
            new_name='settlements_created_8752c1_idx',
            old_name='settlements_batch_mno345_idx',
        ),
        migrations.RenameIndex(
            model_name='settlementbatchitem',
            new_name='settlements_batch_i_e87d97_idx',
            old_name='settlements_item_pqr678_idx',
        ),
    ]
