# Generated by Django 4.2.7 on 2025-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_rename_settlements_order_i_abc123_idx_settlements_order_i_a9932d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='rebate_due_date',
            field=models.DateField(blank=True, help_text='협력사 또는 판매점별로 설정된 리베이트 지급 예정일', null=True, verbose_name='리베이트 지급 예정일'),
        ),
    ]
