# Generated by Django 4.2.7 on 2025-07-22 14:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='주문서의 고유 식별자', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='신청 고객의 성명', max_length=100, verbose_name='고객명')),
                ('customer_phone', models.CharField(help_text='고객 휴대폰 번호', max_length=15, validators=[django.core.validators.RegexValidator(message='올바른 휴대폰 번호를 입력하세요. (예: 010-1234-5678)', regex='^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='연락처')),
                ('customer_email', models.EmailField(blank=True, help_text='고객 이메일 주소 (선택사항)', max_length=254, null=True, verbose_name='이메일')),
                ('model_name', models.CharField(help_text='주문할 스마트기기 모델명', max_length=200, verbose_name='모델명')),
                ('carrier', models.CharField(choices=[('skt', 'SK텔레콤'), ('kt', 'KT'), ('lgu', 'LG유플러스'), ('skt_mvno', 'SK텔레콤 알뜰폰'), ('kt_mvno', 'KT 알뜰폰'), ('lgu_mvno', 'LG유플러스 알뜰폰')], help_text='이용할 통신사', max_length=20, verbose_name='통신사')),
                ('apply_type', models.CharField(choices=[('new', '신규가입'), ('change', '기기변경'), ('transfer', '번호이동'), ('additional', '추가개통')], default='new', help_text='신청의 종류', max_length=20, verbose_name='신청 타입')),
                ('status', models.CharField(choices=[('reserved', '예약'), ('received', '접수'), ('processing', '처리중'), ('completed', '완료'), ('cancelled', '취소')], default='reserved', help_text='주문서의 현재 처리 상태', max_length=20, verbose_name='처리 상태')),
                ('memo', models.TextField(blank=True, help_text='주문 관련 추가 메모', null=True, verbose_name='메모')),
                ('delivery_address', models.TextField(blank=True, help_text='기기 배송받을 주소', null=True, verbose_name='배송 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(help_text='이 주문을 처리하는 업체', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company', verbose_name='처리 업체')),
                ('created_by', models.ForeignKey(blank=True, help_text='주문을 접수한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='접수자')),
                ('policy', models.ForeignKey(blank=True, help_text='이 주문에 적용된 정책', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='policies.policy', verbose_name='적용 정책')),
            ],
            options={
                'verbose_name': '주문서',
                'verbose_name_plural': '주문서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='송장의 고유 식별자', primary_key=True, serialize=False)),
                ('courier', models.CharField(choices=[('cj', 'CJ대한통운'), ('lotte', '롯데택배'), ('hanjin', '한진택배'), ('post', '우체국택배'), ('kdexp', '경동택배'), ('logen', '로젠택배'), ('daesin', '대신택배'), ('etc', '기타')], help_text='배송을 담당하는 택배사', max_length=20, verbose_name='택배사')),
                ('invoice_number', models.CharField(help_text='택배사 송장 추적 번호', max_length=100, verbose_name='송장 번호')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='배송 완료일시')),
                ('recipient_name', models.CharField(blank=True, help_text='실제 택배를 받을 사람 (빈 값이면 고객명 사용)', max_length=100, null=True, verbose_name='수취인명')),
                ('recipient_phone', models.CharField(blank=True, help_text='실제 택배를 받을 사람의 연락처', max_length=15, null=True, verbose_name='수취인 연락처')),
                ('order', models.OneToOneField(help_text='송장이 속한 주문서', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='연관 주문서')),
            ],
            options={
                'verbose_name': '송장',
                'verbose_name_plural': '송장 목록',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='메모의 고유 식별자', primary_key=True, serialize=False)),
                ('memo', models.TextField(help_text='주문 처리 관련 메모나 기록', verbose_name='메모 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('created_by', models.ForeignKey(blank=True, help_text='메모를 작성한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('order', models.ForeignKey(help_text='메모가 속한 주문서', on_delete=django.db.models.deletion.CASCADE, related_name='order_memos', to='orders.order', verbose_name='연관 주문서')),
            ],
            options={
                'verbose_name': '주문 메모',
                'verbose_name_plural': '주문 메모 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_d485bc_idx'), models.Index(fields=['created_by'], name='orders_orde_created_7c6cb8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'status'], name='orders_orde_company_e8f484_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_name', 'customer_phone'], name='orders_orde_custome_026f53_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['model_name'], name='orders_orde_model_n_b68680_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['carrier', 'apply_type'], name='orders_orde_carrier_d6762a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['courier', 'invoice_number'], name='orders_invo_courier_c04463_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sent_at'], name='orders_invo_sent_at_5ae87f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['delivered_at'], name='orders_invo_deliver_812131_idx'),
        ),
    ]
