# Generated by Django 4.2.7 on 2025-08-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100, verbose_name='고객명')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='고객 연락처')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='고객 이메일')),
                ('customer_address', models.TextField(verbose_name='배송 주소')),
                ('status', models.CharField(choices=[('pending', '접수대기'), ('processing', '처리중'), ('shipped', '배송중'), ('completed', '완료'), ('cancelled', '취소'), ('return_requested', '반품요청'), ('exchanged', '교환완료')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 금액')),
                ('rebate_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='리베이트 금액')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='주문 업체')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='주문 생성자')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy', verbose_name='적용 정책')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courier', models.CharField(choices=[('cj', 'CJ대한통운'), ('hanjin', '한진택배'), ('lotte', '롯데택배'), ('logen', '로젠택배'), ('epost', '우체국택배'), ('daesin', '대신택배'), ('hyundai', '현대택배'), ('kg', 'KG로지스'), ('kde', '경동택배'), ('dongbu', '동부택배'), ('other', '기타')], max_length=20, verbose_name='택배사')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='송장번호')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='수취인명')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='수취인 연락처')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='배송완료일시')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '송장',
                'verbose_name_plural': '송장 목록',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('exchange', '교환'), ('cancel', '취소'), ('return', '반품')], max_length=20, verbose_name='요청 유형')),
                ('reason', models.TextField(verbose_name='요청 사유')),
                ('status', models.CharField(choices=[('pending', '요청대기'), ('approved', '승인됨'), ('rejected', '거절됨'), ('completed', '완료')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orders.order', verbose_name='주문')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'verbose_name': '주문 요청',
                'verbose_name_plural': '주문 요청',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'request_type'], name='orders_orde_order_i_99b1c4_idx'), models.Index(fields=['status'], name='orders_orde_status_27e1a0_idx'), models.Index(fields=['created_at'], name='orders_orde_created_1c0807_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memo', models.TextField(verbose_name='메모 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 메모',
                'verbose_name_plural': '주문 메모 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_d485bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['policy'], name='orders_orde_policy__7bd2af_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company'], name='orders_orde_company_c4eb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_name'], name='orders_orde_custome_c16d46_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['courier', 'invoice_number'], name='orders_invo_courier_c04463_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sent_at'], name='orders_invo_sent_at_5ae87f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['delivered_at'], name='orders_invo_deliver_812131_idx'),
        ),
    ]
