# Generated by Django 5.2.4 on 2025-08-02 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_info', models.JSONField(verbose_name='고객 정보')),
                ('status', models.CharField(choices=[('pending', '접수대기'), ('processing', '처리중'), ('shipped', '배송중'), ('completed', '완료'), ('cancelled', '취소'), ('return_requested', '반품요청'), ('exchanged', '교환완료')], default='pending', max_length=20, verbose_name='주문 상태')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='송장번호')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 금액')),
                ('rebate_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='리베이트 금액')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='주문 업체')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy', verbose_name='적용 정책')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100, verbose_name='송장번호')),
                ('courier', models.CharField(max_length=50, verbose_name='택배사')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='배송완료 여부')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='배송완료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '송장',
                'verbose_name_plural': '송장',
            },
        ),
        migrations.CreateModel(
            name='OrderMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='메모 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser', verbose_name='작성자')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 메모',
                'verbose_name_plural': '주문 메모',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('exchange', '교환'), ('cancel', '취소'), ('return', '반품')], max_length=20, verbose_name='요청 유형')),
                ('reason', models.TextField(verbose_name='요청 사유')),
                ('status', models.CharField(choices=[('pending', '요청대기'), ('approved', '승인됨'), ('rejected', '거절됨'), ('completed', '완료')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='주문')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser', verbose_name='처리자')),
            ],
            options={
                'verbose_name': '주문 요청',
                'verbose_name_plural': '주문 요청',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['policy'], name='orders_orde_policy__7bd2af_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company'], name='orders_orde_company_c4eb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='orders_orde_trackin_04edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tracking_number'], name='orders_invo_trackin_50066f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['courier'], name='orders_invo_courier_0dd4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_delivered'], name='orders_invo_is_deli_c622b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermemo',
            index=models.Index(fields=['order'], name='orders_orde_order_i_956357_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermemo',
            index=models.Index(fields=['created_by'], name='orders_orde_created_7c6cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermemo',
            index=models.Index(fields=['created_at'], name='orders_orde_created_9cda7a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['order'], name='orders_orde_order_i_26afaa_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['request_type'], name='orders_orde_request_e2944e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['status'], name='orders_orde_status_27e1a0_idx'),
        ),
    ]
