# Generated by Django 4.2.7 on 2025-08-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_sensitive_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordersensitivedata',
            new_name='orders_orde_order_i_069428_idx',
            old_name='orders_orde_order_i_1f3b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersensitivedata',
            new_name='orders_orde_process_74126c_idx',
            old_name='orders_orde_process_8a7e1c_idx',
        ),
    ]
