# Generated by Django 4.2.7 on 2025-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orders_orde_order_i_1f3b2e_idx_orders_orde_order_i_069428_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_sensitive_data_processed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sensitive_data_key',
        ),
        migrations.AddField(
            model_name='order',
            name='is_sensitive_data_encrypted',
            field=models.BooleanField(default=False, help_text='민감정보가 암호화되어 저장되었는지 여부', verbose_name='민감정보 암호화 완료'),
        ),
    ]
