# Generated by Django 4.2.7 on 2025-08-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_is_sensitive_data_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '접수대기'), ('approved', '승인됨'), ('processing', '처리중'), ('shipped', '배송중'), ('completed', '완료'), ('cancelled', '취소'), ('return_requested', '반품요청'), ('exchanged', '교환완료')], default='pending', max_length=20, verbose_name='주문 상태'),
        ),
    ]
