# Generated by Django 4.2.7 on 2025-08-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('policies', '0011_orderformfield_accept_orderformfield_allow_manual_and_more'),
        ('orders', '0005_add_approved_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='주문의 고유 식별자', primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='자동 생성된 주문번호', max_length=50, unique=True, verbose_name='주문번호')),
                ('current_status', models.CharField(choices=[('received', '접수'), ('activation_request', '개통 요청'), ('activating', '개통중'), ('activation_complete', '개통 완료'), ('cancelled', '취소'), ('pending', '보류'), ('rejected', '반려')], default='received', help_text='주문의 현재 상태', max_length=30, verbose_name='현재 상태')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, help_text='주문 접수 일시', verbose_name='접수일자')),
                ('activation_date', models.DateTimeField(blank=True, help_text='실제 개통 완료 일시', null=True, verbose_name='개통일자')),
                ('carrier', models.CharField(help_text='정책에서 자동 입력', max_length=10, verbose_name='통신사')),
                ('subscription_type', models.CharField(choices=[('MNP', '번호이동'), ('device_change', '기기변경'), ('new', '신규가입')], help_text='정책에서 자동 입력', max_length=20, verbose_name='가입유형')),
                ('order_data', models.JSONField(blank=True, help_text='주문서 양식에서 제출된 모든 데이터', null=True, verbose_name='주문 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(help_text='주문을 접수한 업체', on_delete=django.db.models.deletion.PROTECT, related_name='telecom_orders', to='companies.company', verbose_name='접수 업체')),
                ('created_by', models.ForeignKey(help_text='주문을 접수한 사용자', on_delete=django.db.models.deletion.PROTECT, related_name='created_telecom_orders', to=settings.AUTH_USER_MODEL, verbose_name='접수자 (1차 ID)')),
                ('policy', models.ForeignKey(help_text='적용된 정책', on_delete=django.db.models.deletion.PROTECT, related_name='telecom_orders', to='policies.policy', verbose_name='정책')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='상태 이력의 고유 식별자', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('received', '접수'), ('activation_request', '개통 요청'), ('activating', '개통중'), ('activation_complete', '개통 완료'), ('cancelled', '취소'), ('pending', '보류'), ('rejected', '반려')], help_text='변경된 상태', max_length=30, verbose_name='상태')),
                ('description', models.TextField(blank=True, help_text='상태 변경에 대한 설명', verbose_name='설명')),
                ('user_role', models.CharField(blank=True, help_text='변경자의 역할', max_length=50, verbose_name='사용자 역할')),
                ('department', models.CharField(blank=True, help_text='변경자의 부서', max_length=50, verbose_name='부서')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='변경이 발생한 IP 주소', null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='상태 변경 일시', verbose_name='생성일시')),
                ('order', models.ForeignKey(help_text='상태 이력이 속한 주문', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.telecomorder', verbose_name='주문')),
                ('updated_by', models.ForeignKey(help_text='상태를 변경한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_updates', to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
            ],
            options={
                'verbose_name': '주문 상태 이력',
                'verbose_name_plural': '주문 상태 이력',
                'ordering': ['-created_at'],
            },
        ),
    ]
