# Generated by Django 4.2.7 on 2025-08-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_final_status_and_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderhistory',
            new_name='orders_orde_order_i_f85ce2_idx',
            old_name='orders_orde_order_h_idx',
        ),
        migrations.RenameIndex(
            model_name='orderhistory',
            new_name='orders_orde_to_stat_7ca272_idx',
            old_name='orders_orde_to_stat_h_idx',
        ),
        migrations.RenameIndex(
            model_name='orderhistory',
            new_name='orders_orde_changed_988eb8_idx',
            old_name='orders_orde_changed_h_idx',
        ),
    ]
