# Generated by Django 4.2.7 on 2025-08-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_orders_orde_order_h_idx_orders_orde_order_i_f85ce2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activation_date',
            field=models.DateTimeField(blank=True, help_text='실제 개통 완료 일시', null=True, verbose_name='개통일자'),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='정책에서 자동 입력', max_length=10, verbose_name='통신사'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('adult', '성인일반'), ('corporate', '법인'), ('foreigner', '외국인'), ('minor', '미성년자')], max_length=20, verbose_name='고객유형'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_data',
            field=models.JSONField(blank=True, help_text='주문서 양식에서 제출된 모든 데이터', null=True, verbose_name='주문 데이터'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='자동 생성된 주문번호', max_length=50, null=True, unique=True, verbose_name='주문번호'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='주문 접수 일시', null=True, verbose_name='접수일자'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('MNP', '번호이동'), ('device_change', '기기변경'), ('new', '신규가입')], max_length=20, verbose_name='가입유형'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '접수대기'), ('approved', '승인됨'), ('processing', '개통 준비중'), ('shipped', '개통중'), ('completed', '개통완료'), ('final_approved', '승인(완료)'), ('cancelled', '개통취소'), ('received', '접수'), ('activation_request', '개통 요청'), ('activating', '개통중'), ('activation_complete', '개통 완료'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='from_status',
            field=models.CharField(choices=[('pending', '접수대기'), ('approved', '승인됨'), ('processing', '개통 준비중'), ('shipped', '개통중'), ('completed', '개통완료'), ('final_approved', '승인(완료)'), ('cancelled', '개통취소'), ('received', '접수'), ('activation_request', '개통 요청'), ('activating', '개통중'), ('activation_complete', '개통 완료'), ('rejected', '반려')], max_length=20, verbose_name='이전 상태'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='to_status',
            field=models.CharField(choices=[('pending', '접수대기'), ('approved', '승인됨'), ('processing', '개통 준비중'), ('shipped', '개통중'), ('completed', '개통완료'), ('final_approved', '승인(완료)'), ('cancelled', '개통취소'), ('received', '접수'), ('activation_request', '개통 요청'), ('activating', '개통중'), ('activation_complete', '개통 완료'), ('rejected', '반려')], max_length=20, verbose_name='변경 상태'),
        ),
    ]
