# Generated by Django 4.2.7 on 2025-08-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_migrate_telecom_order_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telecomorder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='telecomorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='telecomorder',
            name='policy',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.DeleteModel(
            name='TelecomOrder',
        ),
    ]
