# Generated by Django 4.2.7 on 2025-08-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_telecomorder_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_id',
            field=models.CharField(blank=True, help_text='주문을 접수한 판매점 코드', max_length=50, verbose_name='1차 ID'),
        ),
    ]
