# Generated by Django 4.2.7 on 2025-08-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_first_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, verbose_name='예금주/카드주'),
        ),
        migrations.AddField(
            model_name='order',
            name='account_number_masked',
            field=models.CharField(blank=True, max_length=100, verbose_name='계좌번호(마스킹)'),
        ),
        migrations.AddField(
            model_name='order',
            name='activation_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='개통번호(마스킹)'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='은행/카드사명'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='카드 브랜드'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_exp_mmyy',
            field=models.CharField(blank=True, max_length=10, verbose_name='카드 유효기간(MMYY)'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number_masked',
            field=models.CharField(blank=True, max_length=100, verbose_name='카드번호(마스킹)'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_period_selected',
            field=models.CharField(blank=True, max_length=10, verbose_name='약정기간(선택)'),
        ),
        migrations.AddField(
            model_name='order',
            name='device_model',
            field=models.CharField(blank=True, max_length=200, verbose_name='단말기 모델'),
        ),
        migrations.AddField(
            model_name='order',
            name='device_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='단말기 일련번호'),
        ),
        migrations.AddField(
            model_name='order',
            name='eid',
            field=models.CharField(blank=True, max_length=50, verbose_name='EID'),
        ),
        migrations.AddField(
            model_name='order',
            name='imei',
            field=models.CharField(blank=True, max_length=50, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='order',
            name='imei2',
            field=models.CharField(blank=True, max_length=50, verbose_name='IMEI2'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='account|card', max_length=20, verbose_name='납부방법'),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='요금상품명'),
        ),
        migrations.AddField(
            model_name='order',
            name='previous_carrier',
            field=models.CharField(blank=True, max_length=20, verbose_name='이전 통신사'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_url',
            field=models.URLField(blank=True, help_text='정책의 외부 URL 스냅샷', max_length=500, null=True, verbose_name='참조 URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='retailer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='판매점명 스냅샷'),
        ),
        migrations.AddField(
            model_name='order',
            name='usim_serial',
            field=models.CharField(blank=True, max_length=50, verbose_name='유심일련번호'),
        ),
        migrations.AddField(
            model_name='ordersensitivedata',
            name='account_number_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='계좌번호 해시'),
        ),
        migrations.AddField(
            model_name='ordersensitivedata',
            name='card_cvc_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='카드 CVC 해시'),
        ),
        migrations.AddField(
            model_name='ordersensitivedata',
            name='card_number_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='카드번호 해시'),
        ),
        migrations.AddField(
            model_name='ordersensitivedata',
            name='rrn_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='주민등록번호 해시'),
        ),
        migrations.AddField(
            model_name='ordersensitivedata',
            name='rrn_masked',
            field=models.CharField(blank=True, max_length=20, verbose_name='주민등록번호(마스킹)'),
        ),
    ]
